<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="MySqlConnector" Version="2.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Yolcu360.EntityLayer\Yolcu360.EntityLayer.csproj" />
    <ProjectReference Include="..\Yolcu360.Common\Yolcu360.Common.csproj" />
  </ItemGroup>

</Project>
